import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
    id("java")
    id("com.github.johnrengelman.shadow") version "8.1.1"
    id("maven-publish")
}

group = "org.teleight"
version = "1.0"

allprojects {
    repositories {
        mavenCentral()
        mavenLocal()

        //TdLight
        maven("https://mvn.mchv.eu/repository/mchv/")
    }
}

dependencies {
    //Tests
    testImplementation(platform("org.junit:junit-bom:5.9.2"))
    testImplementation("org.junit.jupiter:junit-jupiter")

    //Checker
    implementation("org.checkerframework:checker:3.39.0")
    implementation("org.checkerframework:checker-qual:3.39.0")

    //Annotations
    implementation("org.jetbrains:annotations:24.1.0")

    //TdLight
    val tdlightVersion = project.property("tdlight_version");
    compileOnly(platform("it.tdlight:tdlight-java-bom:${tdlightVersion}"))
    compileOnly("it.tdlight:tdlight-java:${tdlightVersion}")
}

sourceSets {
    main {
        java {
            srcDir(file("src/autogenerated/java"))
        }
    }
}

tasks.test {
    useJUnitPlatform()
}

val javadocJar by tasks.registering(Jar::class) {
    archiveClassifier.set("javadoc")
    from(sourceSets.getByName("main").allSource)

    archiveFileName.set("TeleightTd-javadoc.jar")
}

val sourcesJar by tasks.registering(Jar::class) {
    archiveClassifier.set("sources")
    from(sourceSets.getByName("main").allSource)

    archiveFileName.set("TeleightTd-sources.jar")
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            artifactId = "TeleightTd"

            artifact(javadocJar)
            artifact(sourcesJar)

            project.shadow.component(this)
        }
    }
}

tasks.withType<ShadowJar> {
    archiveClassifier.set("")
    archiveVersion.set("")

    archiveFileName.set("TeleightTd.jar")
}
